title: QM QIAU 
description: Quantum mechanics researchs! 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/mosioc/just-the-docs


color_scheme: dark
